[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["insd47"]
license = "MIT"
repository = "https://github.com/insd47/keygrip"

[workspace.dependencies]
aws-sdk-dynamodb = "1"
heck = "0.5"
proc-macro2 = "1"
quote = "1"
serde = { version = "1", features = ["derive"] }
serde_dynamo = { version = "4", features = ["aws-sdk-dynamodb+1"] }
syn = { version = "2", features = ["full"] }
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
